### ISSUE TITLE
"Downloads folder" link in Atelier Schemes is broken

### ISSUE THREAD

**Issue by tim-seoss** [atelierbram/syntax-highlighting#8]
The Atelier schemes github.io page includes the copy
"All downloads can be found in the output folder."

Which includes a link to:

https://github.com/atelierbram/syntax-highlighting/tree/master/atelier-schemes/output

... which is currently a broken link.

**Comment by atelierbram** [comment]
Thanks for this! Fixed now.

**Comment by tim-seoss** [comment]
Still broken for me e.g. here:

https://atelierbram.github.io/syntax-highlighting/atelier-schemes/seaside/#downloads

**Comment by atelierbram** [comment]
Oops ... should be OK now
